-- Run this in Supabase SQL Editor before importing CSV files.

create table if not exists public.fundings (
  funding_id text primary key,
  funding_code text not null unique,
  title text not null,
  full_title text not null,
  organization text not null,
  status_label text not null default 'ทุนวิจัยที่เปิดรับ',
  published_date text not null,
  open_date text not null,
  close_date text not null,
  source_url text,
  details text not null,
  image_path text,
  display_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.funding_attachments (
  id bigint generated by default as identity primary key,
  funding_id text not null references public.fundings (funding_id) on delete cascade,
  file_name text not null,
  file_type text not null check (file_type in ('pdf', 'doc')),
  storage_path text not null,
  file_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists fundings_display_order_idx on public.fundings (display_order);
create index if not exists funding_attachments_funding_id_idx on public.funding_attachments (funding_id, file_order);

alter table public.fundings enable row level security;
alter table public.funding_attachments enable row level security;

drop policy if exists "public read fundings" on public.fundings;
create policy "public read fundings"
on public.fundings
for select
using (true);

drop policy if exists "public read funding_attachments" on public.funding_attachments;
create policy "public read funding_attachments"
on public.funding_attachments
for select
using (true);

-- Optional Storage buckets (create in Dashboard if not exists):
-- funding-images (public)
-- funding-documents (public)
