-- Run this in Supabase SQL Editor to enable multiple detail images per funding.

create table if not exists public.funding_detail_images (
  id bigint generated by default as identity primary key,
  funding_id text not null references public.fundings (funding_id) on delete cascade,
  storage_path text not null,
  image_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists funding_detail_images_funding_id_idx
  on public.funding_detail_images (funding_id, image_order);

alter table public.funding_detail_images enable row level security;

drop policy if exists "public read funding_detail_images" on public.funding_detail_images;
create policy "public read funding_detail_images"
on public.funding_detail_images
for select
using (true);

-- Detail images are stored in the existing public bucket: funding-images
-- Object path pattern: {funding_id}/detail/{order}-{filename}
