-- Researcher core tables for Research Nexus Matching.
-- Run in Supabase SQL Editor before importing researcher data.

create table if not exists public.researchers (
  researcher_id text primary key,
  name_th text not null,
  name_en text,
  department text not null,
  email_raw text,
  phone text,
  scholarly_output integer not null default 0,
  citations integer not null default 0,
  h_index integer not null default 0,
  most_recent_publication_year integer,
  citations_per_publication numeric,
  field_weighted_citation_impact numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.researcher_degrees (
  id bigint generated by default as identity primary key,
  researcher_id text not null references public.researchers (researcher_id) on delete cascade,
  degree_level text not null,
  degree_order integer not null default 0,
  degree_text text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.researcher_expertise (
  id bigint generated by default as identity primary key,
  researcher_id text not null references public.researchers (researcher_id) on delete cascade,
  expertise_order integer not null default 0,
  expertise text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.researcher_keywords (
  id bigint generated by default as identity primary key,
  researcher_id text not null references public.researchers (researcher_id) on delete cascade,
  keyword_type text not null check (keyword_type in ('keyword_en', 'keyword_th')),
  keyword_order integer not null default 0,
  keyword text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.publications (
  publication_id text primary key,
  researcher_id text not null references public.researchers (researcher_id) on delete cascade,
  title text not null,
  source_title text,
  year integer,
  citations integer,
  created_at timestamptz not null default now()
);

create index if not exists researchers_department_idx on public.researchers (department);
create index if not exists researchers_scholarly_output_idx on public.researchers (scholarly_output desc);
create index if not exists researcher_degrees_researcher_id_idx on public.researcher_degrees (researcher_id, degree_order);
create index if not exists researcher_expertise_researcher_id_idx on public.researcher_expertise (researcher_id, expertise_order);
create index if not exists researcher_keywords_researcher_id_idx on public.researcher_keywords (researcher_id, keyword_type, keyword_order);
create index if not exists publications_researcher_id_idx on public.publications (researcher_id, year desc);

alter table public.researchers enable row level security;
alter table public.researcher_degrees enable row level security;
alter table public.researcher_expertise enable row level security;
alter table public.researcher_keywords enable row level security;
alter table public.publications enable row level security;

drop policy if exists "public read researchers" on public.researchers;
create policy "public read researchers"
on public.researchers
for select
using (true);

drop policy if exists "public read researcher_degrees" on public.researcher_degrees;
create policy "public read researcher_degrees"
on public.researcher_degrees
for select
using (true);

drop policy if exists "public read researcher_expertise" on public.researcher_expertise;
create policy "public read researcher_expertise"
on public.researcher_expertise
for select
using (true);

drop policy if exists "public read researcher_keywords" on public.researcher_keywords;
create policy "public read researcher_keywords"
on public.researcher_keywords
for select
using (true);

drop policy if exists "public read publications" on public.publications;
create policy "public read publications"
on public.publications
for select
using (true);
