-- Auto-generated by scripts/researchers/import-scholarly-metrics.mjs
-- Run this in Supabase SQL Editor if direct API update is blocked by RLS.
begin;
update public.researchers
set
  scholarly_output = 53,
  citations = 1395,
  h_index = 20,
  most_recent_publication_year = 2026,
  citations_per_publication = 26,
  field_weighted_citation_impact = 1.65
where researcher_id = 'RS030';
update public.researchers
set
  scholarly_output = 47,
  citations = 768,
  h_index = 15,
  most_recent_publication_year = 2026,
  citations_per_publication = 16,
  field_weighted_citation_impact = 1.36
where researcher_id = 'RS011';
update public.researchers
set
  scholarly_output = 28,
  citations = 402,
  h_index = 12,
  most_recent_publication_year = 2026,
  citations_per_publication = 14,
  field_weighted_citation_impact = 1.11
where researcher_id = 'RS022';
update public.researchers
set
  scholarly_output = 28,
  citations = 190,
  h_index = 9,
  most_recent_publication_year = 2026,
  citations_per_publication = 6,
  field_weighted_citation_impact = 1.86
where researcher_id = 'RS001';
update public.researchers
set
  scholarly_output = 28,
  citations = 120,
  h_index = 5,
  most_recent_publication_year = 2026,
  citations_per_publication = 4,
  field_weighted_citation_impact = 0.6
where researcher_id = 'RS024';
update public.researchers
set
  scholarly_output = 26,
  citations = 199,
  h_index = 8,
  most_recent_publication_year = 2026,
  citations_per_publication = 7,
  field_weighted_citation_impact = 0.58
where researcher_id = 'RS019';
update public.researchers
set
  scholarly_output = 26,
  citations = 165,
  h_index = 8,
  most_recent_publication_year = 2026,
  citations_per_publication = 6,
  field_weighted_citation_impact = 1.2
where researcher_id = 'RS042';
update public.researchers
set
  scholarly_output = 22,
  citations = 187,
  h_index = 6,
  most_recent_publication_year = 2026,
  citations_per_publication = 8,
  field_weighted_citation_impact = 0.96
where researcher_id = 'RS021';
update public.researchers
set
  scholarly_output = 22,
  citations = 66,
  h_index = 5,
  most_recent_publication_year = 2026,
  citations_per_publication = 3,
  field_weighted_citation_impact = 0.73
where researcher_id = 'RS037';
update public.researchers
set
  scholarly_output = 19,
  citations = 89,
  h_index = 6,
  most_recent_publication_year = 2026,
  citations_per_publication = 4,
  field_weighted_citation_impact = 0.58
where researcher_id = 'RS006';
update public.researchers
set
  scholarly_output = 19,
  citations = 150,
  h_index = 6,
  most_recent_publication_year = 2026,
  citations_per_publication = 7,
  field_weighted_citation_impact = 1.18
where researcher_id = 'RS003';
update public.researchers
set
  scholarly_output = 17,
  citations = 460,
  h_index = 8,
  most_recent_publication_year = 2026,
  citations_per_publication = 27,
  field_weighted_citation_impact = 1.66
where researcher_id = 'RS040';
update public.researchers
set
  scholarly_output = 16,
  citations = 309,
  h_index = 7,
  most_recent_publication_year = 2026,
  citations_per_publication = 19,
  field_weighted_citation_impact = 1.04
where researcher_id = 'RS008';
update public.researchers
set
  scholarly_output = 13,
  citations = 55,
  h_index = 4,
  most_recent_publication_year = 2026,
  citations_per_publication = 4,
  field_weighted_citation_impact = 1.06
where researcher_id = 'RS009';
update public.researchers
set
  scholarly_output = 12,
  citations = 23,
  h_index = 3,
  most_recent_publication_year = 2026,
  citations_per_publication = 1,
  field_weighted_citation_impact = 0.42
where researcher_id = 'RS029';
update public.researchers
set
  scholarly_output = 11,
  citations = 164,
  h_index = 7,
  most_recent_publication_year = 2026,
  citations_per_publication = 14,
  field_weighted_citation_impact = 1.88
where researcher_id = 'RS017';
update public.researchers
set
  scholarly_output = 9,
  citations = 115,
  h_index = 7,
  most_recent_publication_year = 2024,
  citations_per_publication = 12,
  field_weighted_citation_impact = 0.68
where researcher_id = 'RS027';
update public.researchers
set
  scholarly_output = 8,
  citations = 22,
  h_index = 2,
  most_recent_publication_year = 2025,
  citations_per_publication = 2,
  field_weighted_citation_impact = 0.1
where researcher_id = 'RS026';
update public.researchers
set
  scholarly_output = 7,
  citations = 127,
  h_index = 3,
  most_recent_publication_year = 2026,
  citations_per_publication = 18,
  field_weighted_citation_impact = 0.92
where researcher_id = 'RS012';
update public.researchers
set
  scholarly_output = 6,
  citations = 112,
  h_index = 3,
  most_recent_publication_year = 2025,
  citations_per_publication = 18,
  field_weighted_citation_impact = 1.08
where researcher_id = 'RS018';
update public.researchers
set
  scholarly_output = 6,
  citations = 45,
  h_index = 3,
  most_recent_publication_year = 2024,
  citations_per_publication = 7,
  field_weighted_citation_impact = 0.66
where researcher_id = 'RS031';
update public.researchers
set
  scholarly_output = 5,
  citations = 46,
  h_index = 2,
  most_recent_publication_year = 2018,
  citations_per_publication = 9,
  field_weighted_citation_impact = 0.41
where researcher_id = 'RS002';
update public.researchers
set
  scholarly_output = 5,
  citations = 33,
  h_index = 2,
  most_recent_publication_year = 2026,
  citations_per_publication = 6,
  field_weighted_citation_impact = 0.83
where researcher_id = 'RS016';
update public.researchers
set
  scholarly_output = 4,
  citations = 37,
  h_index = 2,
  most_recent_publication_year = 2022,
  citations_per_publication = 9,
  field_weighted_citation_impact = 0.45
where researcher_id = 'RS041';
update public.researchers
set
  scholarly_output = 4,
  citations = 23,
  h_index = 3,
  most_recent_publication_year = 2025,
  citations_per_publication = 5,
  field_weighted_citation_impact = 0.44
where researcher_id = 'RS036';
update public.researchers
set
  scholarly_output = 4,
  citations = 32,
  h_index = 2,
  most_recent_publication_year = 2026,
  citations_per_publication = 8,
  field_weighted_citation_impact = 1.43
where researcher_id = 'RS004';
update public.researchers
set
  scholarly_output = 4,
  citations = 48,
  h_index = 2,
  most_recent_publication_year = 2025,
  citations_per_publication = 12,
  field_weighted_citation_impact = 1.64
where researcher_id = 'RS025';
update public.researchers
set
  scholarly_output = 3,
  citations = 63,
  h_index = 1,
  most_recent_publication_year = 2026,
  citations_per_publication = 21,
  field_weighted_citation_impact = 1.76
where researcher_id = 'RS044';
update public.researchers
set
  scholarly_output = 3,
  citations = 77,
  h_index = 1,
  most_recent_publication_year = 2025,
  citations_per_publication = 25,
  field_weighted_citation_impact = 0.27
where researcher_id = 'RS013';
update public.researchers
set
  scholarly_output = 3,
  citations = 7,
  h_index = 2,
  most_recent_publication_year = 2025,
  citations_per_publication = 2,
  field_weighted_citation_impact = 2.2
where researcher_id = 'RS046';
update public.researchers
set
  scholarly_output = 3,
  citations = 17,
  h_index = 3,
  most_recent_publication_year = 2021,
  citations_per_publication = 5,
  field_weighted_citation_impact = 0.26
where researcher_id = 'RS023';
update public.researchers
set
  scholarly_output = 3,
  citations = 2,
  h_index = 1,
  most_recent_publication_year = 2026,
  citations_per_publication = 0,
  field_weighted_citation_impact = 0.1
where researcher_id = 'RS033';
update public.researchers
set
  scholarly_output = 3,
  citations = 3,
  h_index = 1,
  most_recent_publication_year = 2026,
  citations_per_publication = 1,
  field_weighted_citation_impact = 0.14
where researcher_id = 'RS007';
update public.researchers
set
  scholarly_output = 2,
  citations = 3,
  h_index = 1,
  most_recent_publication_year = 2025,
  citations_per_publication = 1,
  field_weighted_citation_impact = 0.24
where researcher_id = 'RS028';
update public.researchers
set
  scholarly_output = 2,
  citations = 4,
  h_index = 2,
  most_recent_publication_year = 2024,
  citations_per_publication = 2,
  field_weighted_citation_impact = 0.79
where researcher_id = 'RS014';
update public.researchers
set
  scholarly_output = 1,
  citations = 6,
  h_index = 1,
  most_recent_publication_year = 2013,
  citations_per_publication = 6,
  field_weighted_citation_impact = 0.19
where researcher_id = 'RS032';
update public.researchers
set
  scholarly_output = 1,
  citations = 0,
  h_index = 0,
  most_recent_publication_year = 2023,
  citations_per_publication = 0,
  field_weighted_citation_impact = 0
where researcher_id = 'RS049';
commit;
