-- Research projects per researcher (imported from Research_Nexus_Database_Ready.xlsx).
-- Run in Supabase SQL Editor before npm run researchers:projects

create table if not exists public.researcher_projects (
  id bigint generated by default as identity primary key,
  researcher_id text not null references public.researchers (researcher_id) on delete cascade,
  project_name text not null,
  role_label text not null,
  project_order integer not null default 0,
  external_project_id text,
  project_status text,
  fiscal_year_be integer,
  created_at timestamptz not null default now()
);

create index if not exists researcher_projects_researcher_id_idx
  on public.researcher_projects (researcher_id, project_order);

create unique index if not exists researcher_projects_unique_idx
  on public.researcher_projects (researcher_id, project_name, role_label);

alter table public.researcher_projects enable row level security;

drop policy if exists "public read researcher_projects" on public.researcher_projects;
create policy "public read researcher_projects"
on public.researcher_projects
for select
using (true);
