-- Run this in Supabase SQL Editor before importing researcher_collaborations.csv

create table if not exists public.researcher_collaborations (
  id bigint generated by default as identity primary key,
  researcher_id text not null,
  organization_name text not null,
  org_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists researcher_collaborations_researcher_id_idx
  on public.researcher_collaborations (researcher_id, org_order);

create unique index if not exists researcher_collaborations_unique_idx
  on public.researcher_collaborations (researcher_id, organization_name);

alter table public.researcher_collaborations enable row level security;

drop policy if exists "public read researcher_collaborations" on public.researcher_collaborations;
create policy "public read researcher_collaborations"
on public.researcher_collaborations
for select
using (true);
